<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Utilities</AssemblyName>
    <RootNamespace>Utilities</RootNamespace>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Ascii85_.cs" />
    <Compile Remove="CueTextBox.cs" />
    <Compile Remove="Data.org.cs" />
    <Compile Remove="DataGridViewEx.cs" />
    <Compile Remove="DropDownList.cs" />
    <Compile Remove="Marquee.cs" />
    <Compile Remove="TransparentTableLayoutPanel.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="8.4.0" />
    <PackageReference Include="protobuf-net" Version="3.2.30" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="8.0.4" />
    <PackageReference Include="System.DirectoryServices" Version="8.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.4" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms">
      <HintPath>..\..\..\..\..\..\..\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.4\ref\net6.0\System.Windows.Forms.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>