// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:Utilities.DataTransferEventArgs._Data")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:Utilities.Extensions.Encoder._digitValues")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:Utilities.ListboxItem._Tag")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:Utilities.Serial._InternalQueue")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:Utilities.Serial._Port")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:Utilities.TriggeredQueue._Lock")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:Utilities.TriggeredQueue._Queue")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:Utilities.TriggeredQueue._Strings")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Ascii85.Decode(System.String)~System.Byte[]")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Ascii85.Encode(System.Byte[])~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Data.BuildQuery(System.String,System.String[],System.String[],System.String,System.String,System.String,System.Boolean)~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Data.ExecuteSQLiteNonQuery(System.String,System.String,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Data.GetCSVData(System.String,System.String[],System.Boolean,System.Collections.Generic.List{System.String},System.String)~System.ValueTuple{System.String,System.Boolean,System.Data.DataTable}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Data.GetMySQLData(System.String,System.String,System.String,System.Int32)~System.ValueTuple{System.String,System.Boolean,System.Data.DataTable}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Data.GetSQLData(System.String,System.String,System.String,System.Int32)~System.Data.DataSet")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Data.GetSQLiteData(System.String,System.String,System.String,System.Int32)~System.ValueTuple{System.String,System.Boolean,System.Data.DataTable}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Data.PageSQLData(System.String,System.String,System.Int32,System.Int32,System.String,System.Int32)~System.Data.DataSet")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.Capitalise(System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.ConstantLengthHash(System.String,System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.CurrentMethodName~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.DeepCopy``1(``0)~``0")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.DictionaryToObject(System.Collections.Generic.IDictionary{System.String,System.Object})~System.Object")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.DictionaryToObject``1(System.Collections.Generic.IDictionary{System.String,System.String},System.Globalization.CultureInfo)~``0")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.GetBuildDateTime(System.Reflection.Assembly,System.TimeZoneInfo)~System.DateTime")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.GetItems(System.Windows.Forms.ListView)~System.Windows.Forms.ListView.ListViewItemCollection")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.GetRandomValue(System.Decimal,System.Decimal,System.Decimal)~System.Decimal")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.LoadFromFile``1(``0,System.String)~``0")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.LoadFromFile``1(``0,System.String,System.Int32)~``0")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.Print(System.IO.FileInfo)")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.ReplaceEx(System.String,System.String,System.String,System.StringComparison)~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.Save``1(``0,System.Boolean)~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.SaveToFile``1(``0,System.String,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.SaveToFile``1(``0,System.String,System.Boolean,System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.ToByteArray(System.Object)~System.Byte[]")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.ToDataTable(System.Type,System.String,System.String)~System.Data.DataTable")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.ToDataTable``1(System.Collections.Generic.List{``0})~System.Data.DataTable")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.ToList(System.Windows.Forms.ListBox.ObjectCollection)~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.ToList(System.Windows.Forms.ListBox.SelectedObjectCollection)~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.ToList``1(System.Windows.Forms.ListBox.ObjectCollection)~System.Collections.Generic.List{``0}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.ToList``1(System.Windows.Forms.ListBox.SelectedObjectCollection)~System.Collections.Generic.List{``0}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.ToObject``1(System.Byte[])~``0")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Serial.Start(System.String,System.Int16)")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.TriggeredQueue.Add(System.Byte)")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.TriggeredQueue.GetQueueData~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.TriggeredQueue.Remove~System.Byte")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.DataTransferEventArgs.StringData")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.Data.Parameters.CreateStatement")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.Data.Parameters.DeleteStatement")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.Data.Parameters.ReadStatement")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.Data.Parameters.UpdateStatement")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.DataTransferEventArgs.Data")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.ListboxItem.Tag")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.ListboxItem.Value")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.StringToObjectMapping`1.DestinationObject")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.StringToObjectMapping`1.Parameters")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.StringToObjectMapping`1.SourceIndex")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.StringToObjectMapping`1.SourceValue")]
[assembly: SuppressMessage("Roslynator", "RCS1085:Use auto-implemented property.", Justification = "<Pending>", Scope = "member", Target = "~P:Utilities.StringToObjectMapping`1.TransformMethodType")]
[assembly: SuppressMessage("Roslynator", "RCS1073:Convert 'if' to 'return' statement.", Justification = "<Pending>", Scope = "member", Target = "~M:Utilities.Extensions.Contains``1(System.Enum,``0)~System.Boolean")]
